### ISSUE TITLE
БУХИС - Контрольная работа по 1С (26.05.2021 защита)

### ISSUE THREAD

**Issue by GeorgiyDemo** [GeorgiyDemo/FA#149]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:////Users/demg/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

<link rel=themeData
href="file:////Users/demg/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:////Users/demg/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_colorschememapping.xml">

</head>

<body lang=en-RU style='tab-interval:36.0pt;word-wrap:break-word'>

<p class=MsoNormal style='text-align:justify'><b style='mso-bidi-font-weight:
normal'><span lang=RU style='font-size:14.0pt;line-height:107%;font-family:
"Times New Roman",serif'>Вариант 6<o:p></o:p></span></b></p>

<p class=MsoNormal style='text-align:justify'><span lang=RU style='font-size:
14.0pt;line-height:107%;font-family:"Times New Roman",serif'>Организация
Контрольная работа (принципал) заключила агентский договор № А04 от 31.03.2021
г. с ООО &quot;Запад&quot; (агент). Принципал поручил агенту приобрести партию
товаров: Сумка-рюкзак 20 шт. по 2500 руб.; Органайзер 50 шт. по 1800 руб. на
общую сумму 168000,00 руб. (в т.ч. НДС 20% - 28000,00 руб.). По условиям
договора, агент выступает от своего имени, но за счет принципала.
Вознаграждение посредника за совершенную сделку включается в стоимость
поступивших товаров и составляет 5% от суммы договора агентирования, что
составляет 8400,00 руб. (в т.ч. НДС 20% - 1400,00 руб.).<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span lang=RU style='font-size:
14.0pt;line-height:107%;font-family:"Times New Roman",serif'>Заполнить таблицу
хозяйственных операций:<o:p></o:p></span></p>

Дата | Операция | Проводка | Сумма | Документы 1С
-- | -- | -- | -- | --
Дт | Кт
Перечисление   денежных средств агенту на покупку товаров
04.04.2021 | Перечисление   денежных средств агенту |   |   | 168000 | Платежное   поручение   Списание   с расчетного счета
Учет   поступления товаров
15.04.2021 | Поступление   товаров |   |   | 140000 | Поступление   (акт, накладная)
15.04.2021 | Учтен   входной НДС |   |   |   |  
15.04.2021 | Зачет   аванса |   |   |   |  
15.04.2021 | НДС   принят к вычету |   |   |   | Счет-фактура полученный
Учет   агентского вознаграждения
15.04.21 | Сумма   агентского вознаграждения учтена в стоимости товаров |   |   | 7000 | Поступление   доп. расходов
15.04.21 | Учтен   входной НДС по агентскому вознаграждению |   |   |   |  
15.04.21 | НДС   принят к вычету |   |   |   |  
Оплата агенту
18.04.21 | Оплата   агентского вознаграждения |   |   | 8400 | Платежное   поручение   Списание   с расчетного счета

<p class=MsoNormal style='text-align:justify'><span lang=RU style='font-size:
14.0pt;line-height:107%;font-family:"Times New Roman",serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span lang=RU style='font-size:14.0pt;line-height:107%;
font-family:"Times New Roman",serif'>Выполнить следующие действия в программе
1С: Бухгалтерия:<o:p></o:p></span></p>

<p class=MsoListParagraphCxSpFirst style='text-indent:-18.0pt;mso-list:l0 level1 lfo1'><![if !supportLists]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman"'><span style='mso-list:Ignore'>1.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif'>Создать
организацию Контрольная работа (справочник Операции)<o:p></o:p></span></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt;mso-list:l0 level1 lfo1'><![if !supportLists]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman"'><span style='mso-list:Ignore'>2.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif'>Создать
контрагента ООО &quot;Запад&quot; и договор с ним № А04 от 31.03.2021 (справочник
Контрагенты)<o:p></o:p></span></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt;mso-list:l0 level1 lfo1'><![if !supportLists]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman"'><span style='mso-list:Ignore'>3.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif'>Внести
в справочник Номенклатура товары: Сумка-рюкзак; Органайзер<o:p></o:p></span></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt;mso-list:l0 level1 lfo1'><![if !supportLists]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman"'><span style='mso-list:Ignore'>4.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif'>Внести
остатки по расчетному счету (Операция, введенная вручную)<o:p></o:p></span></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt;mso-list:l0 level1 lfo1'><![if !supportLists]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman"'><span style='mso-list:Ignore'>5.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif'>Выполнить
в программе операции используя специальные документы.<o:p></o:p></span></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt;mso-list:l0 level1 lfo1'><![if !supportLists]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman"'><span style='mso-list:Ignore'>6.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif'>Сформировать
ОСВ за период – 04.04.21-18.04.21<o:p></o:p></span></p>

<p class=MsoListParagraphCxSpLast style='text-indent:-18.0pt;mso-list:l0 level1 lfo1'><![if !supportLists]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif;
mso-fareast-font-family:"Times New Roman"'><span style='mso-list:Ignore'>7.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp; </span></span></span><![endif]><span
lang=RU style='font-size:14.0pt;line-height:107%;font-family:"Times New Roman",serif'>Сформировать
отчет Анализ субконто (Виды субконто – Контрагенты, Договоры)<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span lang=RU style='font-size:
14.0pt;line-height:107%;font-family:"Times New Roman",serif'>Подготовить отчет
о выполнении контрольной работы, включающий титульный лист, введение – задание
по контрольной работе, часть 1 – теоретические вопросы по учету товаров через
посредника (понятие, основные проводки, документы), часть 2 – скриншоты
выполненных действий в программе 1С: Бухгалтерия.<o:p></o:p></span></p>

</body>

</html>

**Comment by EvgeniiaOg** [comment]
Привет, а есть в итоге решение?

**Comment by GeorgiyDemo** [comment]
> Привет, а есть в итоге решение?

Должна быть, глянь
