### ISSUE TITLE
Практика 5 Python. Структуры, массивы, списки

### ISSUE THREAD

**Issue by GeorgiyDemo** [GeorgiyDemo/FA#35]
Задания:
✅ 1
✅ 2
✅ 3
✅ 4
✅ 5
✅ 6
✅ 7
✅ 8
✅ 9
✅ 10
✅ 11
✅ 12
✅ 13
⚠️ 14 -реализовано без массивов
⚠️ 15 - реализовано без массивов
✅ 16
✅ 17
✅ 18
✅ 19
✅ 20
✅ 21

[Структуры массивы списки - Jupyter Notebook.pdf](https://github.com/GeorgiyDemo/FA/files/4515934/-.Jupyter.Notebook.pdf)

**Comment by Shush1k** [comment]
Гоша молодец, будь как Гоша.

**Comment by GeorgiyDemo** [comment]
> Гоша молодец, будь как Гоша.

Да, спасибо за пару заданий

**Comment by GeorgiyDemo** [comment]
Самая отвратительная практическая на анализ временных ресурсов, спасибо, все.
Вывод из измерений производительности Python: надо прогать на C++
